"""init3

Revision ID: 15b4f25aff80
Revises: 8d927f7a4a87
Create Date: 2025-08-04 16:32:20.308462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b4f25aff80'
down_revision = '8d927f7a4a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_subject_type'), ['subject_type'], unique=False)

    op.drop_table('bank_account_status_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account_status_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('FK__bank_acco__bank___489AC854')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__bank_acc__3213E83FAD3A4126'))
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_subject_type'))
        batch_op.drop_index(batch_op.f('ix_status_history_subject_id'))

    op.drop_table('status_history')
    # ### end Alembic commands ###
