"""init7

Revision ID: 1c49a8c8de99
Revises: b710ff66b542
Create Date: 2025-08-05 14:41:14.559869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c49a8c8de99'
down_revision = 'b710ff66b542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transaction', schema=None) as batch_op:
        batch_op.alter_column('bill_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transaction', schema=None) as batch_op:
        batch_op.alter_column('bill_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
