"""init10

Revision ID: 97d99d3894f1
Revises: fff33922e3d2
Create Date: 2025-08-06 17:34:58.014783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d99d3894f1'
down_revision = 'fff33922e3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_aed_try', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('rate_gbp_try', sa.Numeric(precision=15, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.drop_column('rate_gbp_try')
        batch_op.drop_column('rate_aed_try')

    # ### end Alembic commands ###
