"""init6

Revision ID: b710ff66b542
Revises: d37dbd9aadcd
Create Date: 2025-08-05 14:35:32.592318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b710ff66b542'
down_revision = 'd37dbd9aadcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transaction', schema=None) as batch_op:
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
