"""init4

Revision ID: d37dbd9aadcd
Revises: 15b4f25aff80
Create Date: 2025-08-04 16:49:34.580628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37dbd9aadcd'
down_revision = '15b4f25aff80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeliness_status', sa.Enum('EARLY', 'ON_TIME', 'LATE', name='paymenttimelinessstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('timeliness_status')

    # ### end Alembic commands ###
