"""init8

Revision ID: fff33922e3d2
Revises: 1c49a8c8de99
Create Date: 2025-08-06 11:51:05.835037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff33922e3d2'
down_revision = '1c49a8c8de99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_transaction_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_filename')
    )
    with op.batch_alter_table('expense_transaction_pdf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_transaction_pdf_expense_id'), ['expense_id'], unique=False)

    op.create_table('income_transaction_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_filename')
    )
    with op.batch_alter_table('income_transaction_pdf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_transaction_pdf_income_id'), ['income_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_transaction_pdf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_transaction_pdf_income_id'))

    op.drop_table('income_transaction_pdf')
    with op.batch_alter_table('expense_transaction_pdf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_transaction_pdf_expense_id'))

    op.drop_table('expense_transaction_pdf')
    # ### end Alembic commands ###
