"""status fix

Revision ID: 076b15b0c5a3
Revises: 780a4b2a57d1
Create Date: 2025-07-09 12:21:42.032072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076b15b0c5a3'
down_revision = '780a4b2a57d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=14, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
