"""Add timeliness_status to Income model

Revision ID: 08946e6e6b3e
Revises: de9ca3e072ee
Create Date: 2025-08-04 15:19:23.254324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08946e6e6b3e'
down_revision = 'de9ca3e072ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeliness_status', sa.Enum('EARLY', 'ON_TIME', 'LATE', name='paymenttimelinessstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('timeliness_status')

    # ### end Alembic commands ###
