"""Re-add KMH feature with correct schema

Revision ID: 0cd191b85d0b
Revises: 600d6c0f98e8
Create Date: 2025-07-25 12:44:55.667930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd191b85d0b'
down_revision = '600d6c0f98e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('morning_risk', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('evening_risk', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'entry_date', name='_account_risk_date_uc')
    )
    op.create_table('kmh_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kmh_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('statement_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.Enum('VADESIZ', 'KMH', 'KREDI_KARTI', name='accounttype'), server_default='VADESIZ', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    op.drop_table('kmh_definitions')
    op.drop_table('daily_risks')
    # ### end Alembic commands ###
