"""loans8

Revision ID: 121b95fa35c7
Revises: ae8369c4725a
Create Date: 2025-07-23 12:32:21.614826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121b95fa35c7'
down_revision = 'ae8369c4725a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amortization_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('principal_share', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_share', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_principal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amortization_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amortization_schedule_loan_id'), ['loan_id'], unique=False)

    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amortization_schedule_id', sa.Integer(), nullable=True, comment="Eğer bu bir taksit ödemesiyse, ilgili taksitin ID'si"))
        batch_op.create_foreign_key(None, 'amortization_schedule', ['amortization_schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('amortization_schedule_id')

    with op.batch_alter_table('amortization_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amortization_schedule_loan_id'))

    op.drop_table('amortization_schedule')
    # ### end Alembic commands ###
