"""bank log model updated

Revision ID: 134032d23b13
Revises: b5a1e3d5ade7
Create Date: 2025-07-21 17:56:39.772565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134032d23b13'
down_revision = 'b5a1e3d5ade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banka_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kur_usd_try', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('kur_eur_try', sa.Numeric(precision=15, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banka_log', schema=None) as batch_op:
        batch_op.drop_column('kur_eur_try')
        batch_op.drop_column('kur_usd_try')

    # ### end Alembic commands ###
