"""creditcardcvcskt2

Revision ID: 137313ed08bd
Revises: 3efc463a9d35
Create Date: 2025-07-25 14:33:15.503910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137313ed08bd'
down_revision = '3efc463a9d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('credit_card_no',
               existing_type=sa.VARCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('credit_card_no',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
