"""banklogsrestored

Revision ID: 1f2283994a57
Revises: 137313ed08bd
Create Date: 2025-07-29 13:55:13.690472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2283994a57'
down_revision = '137313ed08bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.Enum('morning', 'evening', name='period'), nullable=False),
    sa.Column('amount_try', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rate_usd_try', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rate_eur_try', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'date', 'period', name='_bank_date_period_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_log')
    # ### end Alembic commands ###
