"""Add payment_day to AccountName table2

Revision ID: 33e27c5ff823
Revises: 6d43859e7764
Create Date: 2025-07-31 16:31:54.391129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e27c5ff823'
down_revision = '6d43859e7764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_name', schema=None) as batch_op:
        batch_op.drop_column('payment_day')

    # ### end Alembic commands ###
