"""creditcardcvcskt

Revision ID: 3efc463a9d35
Revises: 4ecd351d8e3b
Create Date: 2025-07-25 13:50:43.915966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efc463a9d35'
down_revision = '4ecd351d8e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('cvc')

    # ### end Alembic commands ###
