"""init5

Revision ID: 416788060733
Revises: 4ad3a4d9a6fc
Create Date: 2025-07-31 14:43:35.527571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416788060733'
down_revision = '4ad3a4d9a6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_name', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__account_n__payme__6477ECF3'), type_='foreignkey')
        batch_op.drop_column('payment_type_id')

    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__budget_it__accou__7F2BE32F'), type_='foreignkey')
        batch_op.drop_column('account_name_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('FK__budget_it__accou__7F2BE32F'), 'account_name', ['account_name_id'], ['id'])

    with op.batch_alter_table('account_name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('FK__account_n__payme__6477ECF3'), 'payment_type', ['payment_type_id'], ['id'])

    # ### end Alembic commands ###
