"""creditcardno

Revision ID: 4ecd351d8e3b
Revises: 657259eb7f02
Create Date: 2025-07-25 13:48:18.361214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecd351d8e3b'
down_revision = '657259eb7f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_no', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('credit_card_no')

    # ### end Alembic commands ###
