"""bank-logs

Revision ID: 50cdcb906262
Revises: ed812c02ca7f
Create Date: 2025-07-21 20:06:49.245306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cdcb906262'
down_revision = 'ed812c02ca7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.Enum('morning', 'evening', name='period'), nullable=False),
    sa.Column('amount_try', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rate_usd_try', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('rate_eur_try', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'date', 'period', name='_bank_date_period_uc')
    )
    op.drop_table('banka_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banka_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tarih', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=7, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('miktar_try', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('miktar_usd', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('miktar_eur', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('kur_usd_try', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('kur_eur_try', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], name=op.f('FK__banka_log__bank___4D94879B')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__banka_lo__3213E83F9DD2507B'))
    )
    op.drop_table('bank_log')
    # ### end Alembic commands ###
