"""Initial migration

Revision ID: 53f61df46d25
Revises: 
Create Date: 2025-08-08 15:29:15.137975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f61df46d25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_subject_type'), ['subject_type'], unique=False)

    op.create_table('expense_transaction_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_filename')
    )
    with op.batch_alter_table('expense_transaction_pdf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_transaction_pdf_expense_id'), ['expense_id'], unique=False)

    op.create_table('income_transaction_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_filename')
    )
    with op.batch_alter_table('income_transaction_pdf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_transaction_pdf_income_id'), ['income_id'], unique=False)

    op.drop_table('bank_account_status_history')
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_aed_try', sa.Numeric(precision=15, scale=4), nullable=True))
        batch_op.add_column(sa.Column('rate_gbp_try', sa.Numeric(precision=15, scale=4), nullable=True))

    with op.batch_alter_table('credit_card_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_transaction', schema=None) as batch_op:
        batch_op.drop_column('bill_id')

    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.drop_column('rate_gbp_try')
        batch_op.drop_column('rate_aed_try')

    op.create_table('bank_account_status_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('FK__bank_acco__bank___6C190EBB')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__bank_acc__3213E83F25B49C74'))
    )
    with op.batch_alter_table('income_transaction_pdf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_transaction_pdf_income_id'))

    op.drop_table('income_transaction_pdf')
    with op.batch_alter_table('expense_transaction_pdf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_transaction_pdf_expense_id'))

    op.drop_table('expense_transaction_pdf')
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_subject_type'))
        batch_op.drop_index(batch_op.f('ix_status_history_subject_id'))

    op.drop_table('status_history')
    # ### end Alembic commands ###
