"""Add AccountStatusHistory table and relationship

Revision ID: 600d6c0f98e8
Revises: aeca0d8625e6
Create Date: 2025-07-24 11:48:40.511215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600d6c0f98e8'
down_revision = 'aeca0d8625e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('amount', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthly_rate', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('yearly_rate', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('installment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_debt', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_paid', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], name=op.f('FK__loan__bank_id__2B0A656D')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__loan__3213E83F1207FC0B'))
    )
    op.drop_table('account_status_history')
    # ### end Alembic commands ###
