"""Toplam Tutar için currency sütunu eklendi

Revision ID: 6470f86734ea
Revises: 53f61df46d25
Create Date: 2025-08-08 18:02:13.614398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6470f86734ea'
down_revision = '53f61df46d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE income SET currency = 'TRY' WHERE currency IS NULL OR currency NOT IN ('TRY','USD')")
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('currency', existing_type=sa.String(length=3), nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
