"""cardmodels2

Revision ID: 667aa47bb0ef
Revises: 778747611ed5
Create Date: 2025-07-18 17:13:58.740480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667aa47bb0ef'
down_revision = '778747611ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_component_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_brand', schema=None) as batch_op:
        batch_op.drop_column('icon_component_name')

    # ### end Alembic commands ###
