"""cardmodels

Revision ID: 778747611ed5
Revises: 222a8ca830c8
Create Date: 2025-07-18 17:11:47.785188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778747611ed5'
down_revision = '222a8ca830c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'card_brand', ['card_brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('card_brand_id')

    op.drop_table('card_brand')
    # ### end Alembic commands ###
