"""payments

Revision ID: 780a4b2a57d1
Revises: 912ea0438a33
Create Date: 2025-07-09 12:05:42.902463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780a4b2a57d1'
down_revision = '912ea0438a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('UNPAID', 'PAID', 'PARTIALLY_PAID', 'OVERPAID', name='expensestatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('UNPAID', 'PAID', 'PARTIALLY_PAID', 'OVERPAID', name='expensestatus'),
               type_=sa.INTEGER(),
               nullable=True)

    op.drop_table('payment')
    # ### end Alembic commands ###
