"""loans

Revision ID: 786f7f8b2e96
Revises: 50cdcb906262
Create Date: 2025-07-22 11:39:53.310409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786f7f8b2e96'
down_revision = '50cdcb906262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('loan_type_id', sa.Integer(), nullable=False),
    sa.Column('monthly_interest_rate', sa.Float(), nullable=False),
    sa.Column('annual_interest_rate', sa.Float(), nullable=False),
    sa.Column('interest_rules', sa.Text(), nullable=True),
    sa.Column('amount_drawn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_drawn', sa.Date(), nullable=False),
    sa.Column('amount_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_principal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('loan_types')
    # ### end Alembic commands ###
