"""cardmodels3

Revision ID: 7ee4142d3ca8
Revises: 667aa47bb0ef
Create Date: 2025-07-18 17:30:02.681170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee4142d3ca8'
down_revision = '667aa47bb0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_type', schema=None) as batch_op:
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_type', schema=None) as batch_op:
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
