"""init6

Revision ID: 88ae3f744d56
Revises: 416788060733
Create Date: 2025-07-31 16:25:45.113829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ae3f744d56'
down_revision = '416788060733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_aed', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_gbp', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.drop_column('amount_gbp')
        batch_op.drop_column('amount_aed')

    # ### end Alembic commands ###
