"""Add user table

Revision ID: 912ea0438a33
Revises: e3afd4ded6b2
Create Date: 2025-07-08 17:00:57.236175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912ea0438a33'
down_revision = 'e3afd4ded6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
