"""Change payment_day to string for AccountName

Revision ID: 9453de249362
Revises: 33e27c5ff823
Create Date: 2025-07-31 17:08:51.992738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9453de249362'
down_revision = '33e27c5ff823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_name', schema=None) as batch_op:
        batch_op.alter_column('payment_day',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_name', schema=None) as batch_op:
        batch_op.alter_column('payment_day',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
