"""init7

Revision ID: a87e1523ee32
Revises: 33a9296813ae
Create Date: 2025-07-30 13:33:16.026894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87e1523ee32'
down_revision = '33a9296813ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_credit_card_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('morning_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('evening_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_id', 'entry_date', name='_cc_limit_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_credit_card_limits')
    # ### end Alembic commands ###
