"""Add accounts and daily_balances tables

Revision ID: aeca0d8625e6
Revises: 5c7a9669cdcd
Create Date: 2025-07-23 13:46:53.302024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeca0d8625e6'
down_revision = '5c7a9669cdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('iban_number', sa.String(length=34), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'name', name='_bank_account_name_uc'),
    sa.UniqueConstraint('iban_number')
    )
    op.create_table('daily_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('morning_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('evening_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'entry_date', name='_account_date_uc')
    )
 

    # Loan tablosundaki loan_type_id sütununu kaldır
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_constraint('FK__loan__loan_type___2BFE89A6', type_='foreignkey') # Default alembic FK ismi
        batch_op.drop_column('loan_type_id')

    # Şimdi loan_type tablosunu güvenle silebiliriz
    op.drop_table('loan_type')
    # LOAN_TYPE VE LOAN İLE İLGİLİ DÜZELTME SONU

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # LOAN_TYPE VE LOAN İLE İLGİLİ DÜZELTME BAŞLANGICI (downgrade)
    op.create_table('loan_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_type_id', sa.Integer(), nullable=True)) # nullable durumunu kontrol edin
        batch_op.create_foreign_key('FK__loan__loan_type___2BFE89A6', 'loan_type', ['loan_type_id'], ['id']) # Kısıtlama adını kontrol edin
    # LOAN_TYPE VE LOAN İLE İLGİLİ DÜZELTME SONU (downgrade)

    op.drop_table('daily_balances')
    op.drop_table('accounts')
    # ### end Alembic commands ###