"""Update BankAccountStatusHistory to StatusHistory

Revision ID: b2b34f71a353
Revises: 01e538064045
Create Date: 2025-08-04 15:48:55.889487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b34f71a353'
down_revision = '01e538064045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_subject_type'), ['subject_type'], unique=False)

    op.drop_table('bank_account_status_history')
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_aed', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_gbp', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.drop_column('amount_gbp')
        batch_op.drop_column('amount_aed')

    op.create_table('bank_account_status_history',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('FK__bank_acco__bank___6A30C649')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__bank_acc__3213E83FB260F9B1'))
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_subject_type'))
        batch_op.drop_index(batch_op.f('ix_status_history_subject_id'))

    op.drop_table('status_history')
    # ### end Alembic commands ###
