"""kmh manuel-autofilled

Revision ID: b48ad50c396a
Revises: 3f1770cb3902
Create Date: 2025-08-01 17:24:07.053023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48ad50c396a'
down_revision = '3f1770cb3902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), server_default='manual', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_risks', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
