"""bank log model

Revision ID: b5a1e3d5ade7
Revises: 7ee4142d3ca8
Create Date: 2025-07-21 16:36:39.699689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a1e3d5ade7'
down_revision = '7ee4142d3ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banka_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('period', sa.Enum('morning', 'evening', name='period'), nullable=False),
    sa.Column('miktar_try', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('miktar_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('miktar_eur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'tarih', 'period', name='_bank_tarih_period_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banka_log')
    # ### end Alembic commands ###
