"""Recreate migrations for existing database

Revision ID: de9ca3e072ee
Revises: 
Create Date: 2025-08-01 14:38:13.773449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9ca3e072ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_aed', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_gbp', sa.Numeric(precision=15, scale=2), nullable=True))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        batch_op.drop_column('amount_gbp')
        batch_op.drop_column('amount_aed')

    # ### end Alembic commands ###
