"""initial bank and bank_log tables

Revision ID: df8339ebfadd
Revises: 
Create Date: 2025-07-20 19:05:36.385672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8339ebfadd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bank_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('morning_amount_try', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('evening_amount_try', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('morning_amount_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('evening_amount_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('morning_amount_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('evening_amount_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_log')
    op.drop_table('bank')
    # ### end Alembic commands ###
