"""Add remaining_amount to expense

Revision ID: e3afd4ded6b2
Revises: a8b82e2e12fd
Create Date: 2025-07-08 15:07:10.639479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3afd4ded6b2'
down_revision = 'a8b82e2e12fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('remaining_amount')

    # ### end Alembic commands ###
