"""banlogs

Revision ID: fe9084e4d8be
Revises: 55e1d85aa85d
Create Date: 2025-07-24 10:59:04.474179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9084e4d8be'
down_revision = '55e1d85aa85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        # Drop the old unique constraint
        batch_op.drop_constraint('_bank_date_period_uc', type_='unique')
        
        # Add the new column and create the foreign key
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_bank_log_bank_account', 'bank_account', ['bank_account_id'], ['id'])
        
        # Drop the old foreign key and column
        batch_op.drop_constraint('FK__bank_log__bank_i__5BE2A6F2', type_='foreignkey')
        batch_op.drop_column('bank_id')

        # Create the new unique constraint
        batch_op.create_unique_constraint('_bank_account_date_period_uc', ['bank_account_id', 'date', 'period'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_log', schema=None) as batch_op:
        # Drop the new unique constraint
        batch_op.drop_constraint('_bank_account_date_period_uc', type_='unique')

        # Add the old column and create the foreign key
        batch_op.add_column(sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__bank_log__bank_i__5BE2A6F2', 'bank', ['bank_id'], ['id'])

        # Drop the new foreign key and column
        batch_op.drop_constraint('fk_bank_log_bank_account', type_='foreignkey')
        batch_op.drop_column('bank_account_id')

        # Create the old unique constraint
        batch_op.create_unique_constraint('_bank_date_period_uc', ['bank_id', 'date', 'period'])

    # ### end Alembic commands ###
