export const mockCreditCards = [
  {
    id: 1,
    bankName: 'Yapı Kredi',
    cardName: 'World Platinum',
    cardType: 'Mastercard',
    limit: 250000.00,
    risk: 65965.89,
    statementDay: 27,
    paymentDueDay: 6,
  },
  {
    id: 2,
    bankName: 'QNB Finansbank',
    cardName: 'CardFinans',
    cardType: 'Mastercard',
    limit: 750000.00,
    risk: 120230.12,
    statementDay: 28,
    paymentDueDay: 8,
  },
  {
    id: 3,
    bankName: 'Ziraat Bankası',
    cardName: 'Bankkart Başak (Anakart)',
    cardType: 'Troy',
    limit: 1150000.00,
    risk: 140526.98,
    statementDay: 25,
    paymentDueDay: 4,
  },
  {
    id: 4,
    bankName: 'İş Bankası',
    cardName: 'Maximum Premier',
    cardType: 'Visa',
    limit: 500000.00,
    risk: 475479.28,
    statementDay: 23,
    paymentDueDay: 2,
  },
    {
    id: 5,
    bankName: 'Vakıfbank',
    cardName: 'Platinum',
    cardType: 'Mastercard',
    limit: 200000.00,
    risk: 32152.58,
    statementDay: 3,
    paymentDueDay: 13,
  },
  {
    id: 6,
    bankName: 'TEB',
    cardName: 'Bonus Card',
    cardType: 'Visa',
    limit: 500000.00,
    risk: 1800.97,
    statementDay: 7,
    paymentDueDay: 17,
  }
];
